name: hello_world_dart_command
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

# Version de dart que sea compatible
environment:
  sdk: ^3.2.4

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
